name: Deploy to Scalingo

on:
  push:
    tags:
      - 'deploy-backend-*'  # Se déclenche uniquement pour les tags qui commencent par "deploy-backend-"
      
jobs:
  scalingo-deploy:
    runs-on: ubuntu-latest
    env:
      SCALINGO_APP_NAME: ymchat
      SCALINGO_REGION: osc-fr1
      PROJECT_DIR: backend
      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }} # stocke le token dans GitHub Secrets
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # équivalent à GIT_DEPTH: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3

      - name: Install Scalingo CLI
        run: |
          curl -O https://cli-dl.scalingo.com/install && bash install

      - name: Set PROJECT_DIR env var on Scalingo
        run: |
          scalingo --app=$SCALINGO_APP_NAME env-set PROJECT_DIR=$PROJECT_DIR

      - name: Login to Scalingo
        run: |
          scalingo login --api-token $SCALINGO_API_TOKEN

      - name: Generate SSH key pair
        run: |
          mkdir -p ~/.dpl
          ssh-keygen -t rsa -N "" -C $HOSTNAME -f ~/.dpl/id_rsa

      - name: Add SSH key to Scalingo
        run: |
          scalingo keys-remove dpl_tmp_key || echo "On la supprime au préalable"
          scalingo keys-add dpl_tmp_key ~/.dpl/id_rsa.pub

      - name: Setup Scalingo git remote
        run: |
          scalingo --app $SCALINGO_APP_NAME git-setup --remote scalingo-dpl --force

      - name: Push to Scalingo
        run: |
          GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=no -i ~/.dpl/id_rsa' \
          git push scalingo-dpl HEAD:refs/heads/main -f

      - name: Remove SSH key from Scalingo
        run: |
          scalingo keys-remove dpl_tmp_key || echo "Suppression"
